### ISSUE TITLE
Conditional?

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csl-next-attic#23]
In the v1.1 branch, we adapted a richer conditional from CSL-M.

Could maybe adapt that further for something simpler/more concise?

https://github.com/citation-style-language/schema/blob/master/schemas/styles/csl-choose.rnc

**Comment by bdarcus** [comment]
I ended up adding something inspired partly by this, but also by lisp (in particular clojure and scheme) and XSLT 3.0 in:

https://github.com/bdarcus/csl-next/commit/3ab2ba89ef4127bcee4f1c950b331523cd451f12

It only offers the element-based model, and has just `cs:when` and `cs:else`.

**Comment by denismaier** [comment]
How will that look like in practice? Do you have an example?

**Comment by bdarcus** [comment]
Though maybe it's not so much v1.1.

https://github.com/bdarcus/csl-next/blob/9c6f88ecd6b2e5906f47653c400722810454325f/examples/style.xml#L12-L31
